# Generated by Django 5.0.6 on 2024-06-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_rename_curos_cursos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
    ]
